### ISSUE TITLE
More font types

### ISSUE THREAD

**Issue by ShiveStar** [Xinyuan-LilyGO/T-0.99TFT#2]
Hi Lilygo, I am looking to purchase a few of these, however, it seems like only one font is available and it's too big for my purposes. Will more fonts be made in the future or is there a place to get more fonts for this display? Thanks!

**Comment by LilyGO** [comment]
Hi，You can modulo by font. Use the size that feels right to you. It doesn't matter if you use portrait orientation. But the landscape compatibility of this screen is not perfect. It is recommended that you use the lvgl implementation. lvgl has to rotate fonts by software.

**Comment by ShiveStar** [comment]
> Hi，You can modulo by font. Use the size that feels right to you. It doesn't matter if you use portrait orientation. But the landscape compatibility of this screen is not perfect. It is recommended that you use the lvgl implementation. lvgl has to rotate fonts by software.

How should I go about modulo the font? Is this correct:
#ifdef  CHAR_FONT_W8_H16
#define  FONT_W  8%12
#define  FONT_H  16%12
#endif

**Comment by LilyGO** [comment]
yes

**Comment by ShiveStar** [comment]
> yes

I tried that today with my newly arrive display and it has no visible affect besides creating severe text distortions (aka text is either not displayed or its just dots on the screen). Can you confirm this is a working feature?

**Comment by LilyGO** [comment]
A software algorithm is required to rotate the font

**Comment by ShiveStar** [comment]
> A software algorithm is required to rotate the font

Is there a method for shrinking the font that doesn’t involve revolving display. All I am in looking for is to use the display in landscape mode with a smaller font size than is currently provided. I attempted Modulo as instructed but the display did not display anything. Can I shrink the font while maintaining landscape perspective ?

**Comment by LilyGO** [comment]
Using LVGL is a good choice

**Comment by ShiveStar** [comment]
> Using LVGL is a good choice

Could you provide an example for implementing LVGL? This display driver doesn't seem to be supported
